### ISSUE TITLE
spectre.[css|js] returns 404

### ISSUE THREAD

**Issue by da2x** [alexwlchan/specktre#6]
… as does the generated image.

https://alexwlchan.net/tools/specktre/

**Comment by alexwlchan** [comment]
Well that thoroughly sucks. Probably fixable, but I don’t really have time to work on this right now.

I’ll stick it on my TODO list.

Thanks for letting me know!

**Comment by alexwlchan** [comment]
New plan: this has been broken for months and I’ve only had one complaint about it. That’s a strong indicator that nobody is actually using the site (I really don’t advertise it much, and I don’t have much motivation to work on it these days), so I’m just going to take it down.
